# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05db5a2e5511441328ee977b07db5b77ed6e5559e7bcef292ecdcf8ccc7f158bec94f029d6cf1d45e27e5d26ffa06e3cea90ad8ea78326420ea8bdf8e39e8280

test:
  secret_key_base: 5bfcd6f33c2a717f31043b98c2e070e967eb84b01458d4d98c7f8001806df1b7d256e104f9296f12f36aeb88e0bebed6afd27034e598515bdff5f5c3b756a2a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
